apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatarm64-deployment
  namespace: fccltest
  labels:
    app: tomcatarm64
  annotations:
   kubernetes.io/change-cause: image updated to 8.5.41-jdk11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcatarm64
  template:
    metadata:
      labels:
        app: tomcatarm64
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
      tolerations:
      - effect: NoSchedule
        key: jetson
        operator: Equal
        value: "true"
      containers:
      - name: tomcatarm64
        image: 192.168.131.125:8085/arm64/tomcat:8.5.41-jdk11
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: my-secret
---
apiVersion: v1
kind: Service
metadata:
  name: tomcatarm64
  namespace: fccltest
  labels:
    name: tomcatarm64
spec:
  type: NodePort
  selector:
    app: tomcatarm64
  ports:
    # the port that this service should serve on
    - port: 8080
      targetPort: 8080
      name: tomcatarm64-8080
